DELIMITER $$ 
DROP TRIGGER IF EXISTS aftUpdCliente $$
CREATE TRIGGER aftUpdCliente AFTER UPDATE ON Cliente 
FOR EACH ROW
BEGIN 
    
END $$

DELIMITER $$
DROP TRIGGER IF EXITS befInsCliente $$
CREATE TRIGGER befInsCliente BEFORE INSERT ON Cliente
FOR EACH ROW 
BEGIN

END $$